name: Frontend Build Check

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**" # Runs only when frontend files are modified

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend # Set working directory to frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use the required Node.js version
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Verify Build Output
        run: ls -l build || ls -l dist # Check if build folder exists (adjust based on framework)
